### ISSUE TITLE
How can i play with specific time

### ISSUE THREAD

**Issue by ArunDevOpsiOS** [MillmanY/MMPlayerView#1]
How can I play MMPlayerview with the Specific seek time? I'm playing video in the TableViewcell I need to have videos play where they are paused while scrolling. So I'm asking where can I do that in the code?

**Comment by MillmanY** [comment]
Try to set this
playerLayer.cacheType = .memory(count: 10)

public enum MMPlayerCacheType {
    case none
    case memory(count: Int)
}

It will cache player last status on this url, when change another video and back this url ,will play the last status where video stop 

version:
pod "MMPlayerView"   , '~> 2.0.5'

**Comment by ArunDevOpsiOS** [comment]
Thanks for the quick reply. It helped me solved that thing. Super thanks for this...

**Comment by MillmanY** [comment]
Its okay, If you have any problem ,just let me know 👍
