### ISSUE TITLE
Change video while in full screen

### ISSUE THREAD

**Issue by Aragunz** [MillmanY/MMPlayerView#11]
Can I change video url and video, while i am in full screen, basically if i have autoplay and i am in full screen to go from one video in next without the need to leave full screen? 
Thank you @MillmanY

**Comment by MillmanY** [comment]
1. Create fullscreen class



    class FullScreenPlayerViewController: UIViewController {

       class func xibWith(player: ETPlayerLayer) -> FullScreenPlayerViewController {
            let s = UIStoryboard(name: "Video", bundle: nil)
            let vc = s.instantiateViewController(withIdentifier: "FullScreenPlayerViewController")
           (vc as? FullScreenPlayerViewController)?.player = player
            vc.view.backgroundColor = UIColor.black
           return vc as! FullScreenPlayerViewController
       }

       var urlList =  [URL]()
       weak var player: ETPlayerLayer?

       override func viewDidLoad() {
          super.viewdidLoad()
          self.playAt(idx: 0)
       }
  
       func playAt(idx: Int) {

            if idx >= urlList.count {
               return
            }
            playLayer.set(url: urlList[idx]) { [weak self] (status) in
                switch status {
                case .end
                  self?.playAt(idx: idx+1)
                 default: break
               }
           }
       }
     }       

 let vc = FullScreenPlayerViewController.xibWith(player: self.playLayer)
        
        MMLandscapeWindow.shared.makeKey(root: vc, playLayer: self.playLayer, completed: { [weak self] in
             //  do.... something

        })

And then you have player reference in Full screen when you excute some action change your url use
playLayer.set(url:.......  ,
