### ISSUE TITLE
Example for push transition 

### ISSUE THREAD

**Issue by jasminpsimform** [MillmanY/MMPlayerView#12]
Thanks a lot for the great library.

can you please provide code or example for push transition?

**Comment by MillmanY** [comment]
self.mmPlayerTransition.push.pass { (_) in}
        let story = UIStoryboard(name: "Video", bundle: nil)
        if let vc = story.instantiateViewController(withIdentifier: "Video") as? VideoViewController {
            self.navigationController?.pushViewController(vc, animated: true)
        }

**Comment by jasminpsimform** [comment]
Thanks a lot MillmanY.
Again thanks for the library.

**Comment by MillmanY** [comment]
Your welcome,If you have any issue just let me know :D

**Comment by jasminpsimform** [comment]
yeah sure.
