### ISSUE TITLE
How to use MMPlayerLayer in Tableview

### ISSUE THREAD

**Issue by alizainprasla** [MillmanY/MMPlayerView#13]
I have used MMPlayerLayer in tableview cell

```
mmPlayerLayer.playView = cell.imgView
mmPlayerLayer.set(url: cell.data?.play_Url, state: { (status) in 
})
mmPlayerLayer.startLoading()
```

Like 

```
func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        
        guard let resource = Bundle.main.path(forResource: "video", ofType: "mp4") else {
            print("VIDEO ERROR")
            return
        }
        //
        let url = URL.init(fileURLWithPath: resource)
        
        let cell = self.tableView.cellForRow(at: indexPath) as! VideoCell
        mmPlayerLayer.playView = cell.imgView
        mmPlayerLayer.set(url: url, state: { (status) in
        })
        mmPlayerLayer.startLoading()
        

    }
```

on scrolling its showing on other cell too. what am i doing wrong?

**Comment by Aragunz** [comment]
I think the default example is completely implemented on tableView, the example would be a great start.

**Comment by MillmanY** [comment]
I was been busy these days, so i didnt reply you :(
If you have any question, just let me know ~

**Comment by alizainprasla** [comment]
@MillmanY. Dequeuing issue is fixed. i have question too.

1) the way i implement it is right way?
2) I am not able to see control in cells?

**Comment by alizainprasla** [comment]
@Aragunz Yes its working fine. i had dequeuing issue. but its not showing controls. i don't want it autoplay

**Comment by annjawn** [comment]
@MillmanY @Aragunz could you guys please share an example on how to use it in a TableViewCell?
