### ISSUE TITLE
How to stop play video, if there is not only video types in collectionView there are images types also?

### ISSUE THREAD

**Issue by MandeepSingh1** [MillmanY/MMPlayerView#14]
Hi am also using the same way to Play Video in Collection View. There is a list of images and videos showing in collection view.
     
     [ Video type ]
     [ Image type ]
     [ Video type ]
     [ Video type ]
     [ Video type ]
     [ Image type ]
     [ Image type ]
     
     fileprivate func updateCell(at indexPath: IndexPath) {
     
     if let cell = self.collectionView!.cellForItem(at: indexPath) as? TimelineFeedCell {
     // this thumb use when transition start and your video dosent start
     
     let postDict = self.arrayPostData[indexPath.item]
     
     print(indexPath.item)
     
     if postDict.video_flag == 0 {
     
     mmPlayerLayer.playView = nil
     mmPlayerLayer.player?.pause()
     mmPlayerLayer.playUrl = nil
     
     } else {
     
     mmPlayerLayer.thumbImageView.image = cell.postImageView.image
     // set video where to play
     if !MMLandscapeWindow.shared.isKeyWindow {
     mmPlayerLayer.playView = cell.postImageView
     }
     
     // set url prepare to load
     mmPlayerLayer.set(url: URL(string: cell.postModelInfo?.image_url ?? ""), state: { (status) in
     switch status {
     case .failed(let err):
     print("err", err)
     case .ready:
     print("Ready to Play")
     case .playing:
     print("Playing")
     case .pause:
     print("Pause")
     case .end:
     print("End")
     default: break
     }
     })
     }
     }
     }
     
     Am using your function but Still am not able to stop the previous cell of video. Video is still playing but my current cell is of image. How can I resolve this issue. Please Help me

**Comment by MillmanY** [comment]
1. mmPlayerLayer.player?.pause()
2. mmPlayerLayer.playView = nil
3. mmPlayerLayer.playUrl = nil
choose one, I prefer you to use method2 ,when image type just set view nil

**Comment by MandeepSingh1** [comment]
No Sir, still playing the video rather then video cell is not visible. My Video cell is at 0 index and my current cell index is 2 still I can hear the voice of that video.

**Comment by MillmanY** [comment]
Are you only have one player ?
You need control only one player and reset to cell

**Comment by MillmanY** [comment]
When is updateCell function call ??

**Comment by MandeepSingh1** [comment]
When I scroll the collection view

**Comment by MillmanY** [comment]
I know , I mean which function when you call updateCell

**Comment by MandeepSingh1** [comment]
Let me show you my code 

     override func viewDidAppear(_ animated: Bool) {
        
        self.collectionView!.addObserver(self, forKeyPath: "contentOffset", options: [.new], context: nil)

    }

       override func observeValue(forKeyPath keyPath: String?, of object: Any?, change: [NSKeyValueChangeKey : Any]?, context: UnsafeMutableRawPointer?) {
        if keyPath == "contentOffset" {
            self.updateByContentOffset()
            NSObject.cancelPreviousPerformRequests(withTarget: self)
            self.perform(#selector(startLoading), with: nil, afterDelay: 0.3)
            
        } else {
            super.observeValue(forKeyPath: keyPath, of: object, change: change, context: context)
        }
    }
    
    fileprivate func updateByContentOffset() {
        
        let p = CGPoint(x: self.collectionView!.frame.width/1.2, y: self.collectionView!.contentOffset.y + self.collectionView!.frame.width/1.2)
        
        if let path = self.collectionView!.indexPathForItem(at: p),
            self.presentedViewController == nil {
            self.updateCell(at: path)
        }
    }

Here is am calling the updated cell function

**Comment by MandeepSingh1** [comment]
Like in Instagram there is only one video cell or image cell is showing on the iPhone Screen. Am also showing on the same way and video is playing perfectly. But when I scroll the collection view and moves to next cell which contains image then its still playing previous video.

**Comment by MillmanY** [comment]
Can help me to check your playView = nil its call? when do this after your code will reset your video ?
Are you check your postDict.video_flag value ?

**Comment by MandeepSingh1** [comment]
Sorry, I didn't understand what you said. Can you bit clearly regarding your question. So that both of us are on the same page.

**Comment by MillmanY** [comment]
Im sure when call playerLayer.playView = nil video will stop, so I want you check your parameter
postDict.video_flag == 0 ?
 if postDict.video_flag == 0 {
  // 
}

**Comment by MandeepSingh1** [comment]
Okay just give me 2 minutes.

**Comment by MandeepSingh1** [comment]
I check it postDict.video_flag is perfect. When it comes to another cell means when collection view goes to Image cell. This line of code is execute and it plays the video. I debug it cache item plays the video.

          if let myItem = self.cahce.getItem(key: url) {
                
                print("manu",myItem.status)
            }
            
            if let cacheItem = self.cahce.getItem(key: url) , cacheItem.status == .readyToPlay {
                self.asset = (cacheItem.asset as? AVURLAsset)
                self.player?.replaceCurrentItem(with: cacheItem)
            }

**Comment by MillmanY** [comment]
When "Image type" your video its play on this cell or previous "video type" cell ?
If you play on "Image type" , I think you set playerLayer.playView = nil timing its not correct

**Comment by MandeepSingh1** [comment]
In Previous Video Cell.

Please add this check in your sdk. Then we can resolve the issue, my issue has been resolved but you have to update in your SDK as well.

                   if let cacheItem = self.cahce.getItem(key: url) , cacheItem.status == .readyToPlay {
                
                           if playView != nil {
                             self.asset = (cacheItem.asset as? AVURLAsset)
                            self.player?.replaceCurrentItem(with: cacheItem)
                        }
                   }

**Comment by MandeepSingh1** [comment]
Actually, Cache item is occurring the issue for playing the videos in previous cell. Your SDK is Awesome. I have one more issue Can you help me. When we play the videos in collection view cell I have a comment button. When user press on it, it will push to another screen how can I stop the video to playing using navigation Controller.

**Comment by MillmanY** [comment]
1.Okay , I know what's the problem it happen, I will fix it
2.viewWillDisappear to pause ? (mmPlayerLayer.player.pause)

**Comment by MandeepSingh1** [comment]
And I want to Give you advice that in your demo. You have to show the combination of images and videos. So that user can easily use your SDK.

**Comment by MillmanY** [comment]
Okay, thanks a lot for your advice,I' will improve it!!

**Comment by MandeepSingh1** [comment]
Thanks a lot man, your SDK teach me a lot. Thanks for helping us.

**Comment by MandeepSingh1** [comment]
Hey @MillmanY , when I pushing the view controller to another view controller, how can I pass the mmplayerView values to another controller so that same video will play to detail Screen. You have provide the example of present. How can we achieve using push or Segue
