### ISSUE TITLE
Resume immediately when the video already played

### ISSUE THREAD

**Issue by nvduc2910** [MillmanY/MMPlayerView#19]
Hello Sir. 

Thank your for library. 

I have an issue , for now I still don't know how to control that. I want to resume video immediately when scroll down or scroll up. (like Facebook) (apply this for the video already playing then pause state). 

I have just try to put MMPlayerLayer in each cell then when cell is invisible I set it's pause then play it again when that cell visible but really laggy. 

In this library seems to cache the last time of video then init and play with that time. but in this way I need to wait indicator loading. 

One more thing. I really want to keep the last thumb when the video pause. 

Can you help me. 

Thank you so much.

**Comment by MillmanY** [comment]
Hi, I suggest only one player in UITableView or UICollectionView, if you have more then one player it will be lag

**Comment by MillmanY** [comment]
Hi I'm fix cache issue in 3.0.9
you can call stopLoading where your cell don't want to play the video

**Comment by nvduc2910** [comment]
Thank you. let me check.

How about idea to capture thumb of video so when scroll previous video it's will be more suitable and smooth

**Comment by Simerpal** [comment]
@MillmanY  I have an issue , for now I still don't know how to solve that. 
Issue: -  Play video immediately on scrolling of tableview.
