### ISSUE TITLE
How to MMPlayerlayer from playing if Pushing new viewcontroller

### ISSUE THREAD

**Issue by ArunDevOpsiOS** [MillmanY/MMPlayerView#2]
I'm using MMplayerLayer for viewing images in table view, But it won't stop even after pushing new controller. How can I make it stop from playing if pushing new Controller.

**Comment by MillmanY** [comment]
Implement Protocol and when completed call playerLayer.player.pause

**Comment by ArunDevOpsiOS** [comment]
I already have written this in viewDidDisapear but this doesn't work.Looks like there is some other problem as well.

**Comment by MillmanY** [comment]
##ver 2.1.2 Fix

Thanks for reply, I have been to fix this issue , when you push/present controller you will get function "func transitionCompleted(player: MMPlayerLayer)" and you can get this variable to put in your variable , and if you use navigation push you need write this self.mmPlayerTransition.push.pass { (_) in} on first controller not second
