### ISSUE TITLE
Always get blank black color before play

### ISSUE THREAD

**Issue by nvduc2910** [MillmanY/MMPlayerView#20]
Hello, 

 When the video ready to play I always get the blank black color before play video. Can you let me know why.

Thank you so much.

Change the background Of AvPlayer.

**Comment by khush004** [comment]
@nvduc2910 Did you get any solution?

**Comment by ducnv2910** [comment]
Change the background Of AvPlayer.

**Comment by khush004** [comment]
@ducnv2910 I don't want to display that different color's background too. I just want to play video without Blinking the page. Please help!

**Comment by ducnv2910** [comment]
set background of avplayer to clear color.

**Comment by khush004** [comment]
Thank you so much 👍
