### ISSUE TITLE
Play video not working in new viewcontroller.

### ISSUE THREAD

**Issue by nvduc2910** [MillmanY/MMPlayerView#21]
Hello,

I am trying to play a video in other viewcontroller not in UICollectionview by this method.

func playVideo(urlStr: String){

        self.playerLayer?.stopLoading()
        
        if !MMLandscapeWindow.shared.isKeyWindow{
            mmPlayerLayer.playView = self.ivScoop
        }
        
        // set url prepare to load
        
        mmPlayerLayer.set(url: URL(string: (Constant.URL_VIDEO_SCOOP_END_POINT + urlStr)), state: { (status) in
            switch status{
                
            case .ready:
                print("ready to play")
            case .unknown:
                print("unknown")
            case .failed(let err):
                print("eroror")
            case .playing:
                print("playing")
            case .pause:
                print("pause")
            case .end:
                break
                
            }
        })
    }

But it's not working. and status is just unknow . 

Please help me. 

Thank you very much.

**Comment by MillmanY** [comment]
mmPlayerLayer.set(url: URL(string: (Constant.URL_VIDEO_SCOOP_END_POINT + urlStr)), state: { (status) in
         ......
        }
    })

// This line you forgot it
-> mmPlayerLayer.startLoading()

**Comment by nvduc2910** [comment]
oh. my bad. Thank you so much. love you :)
