### ISSUE TITLE
When I click 2. row it plays 1.row ?

### ISSUE THREAD

**Issue by ismailtosun** [MillmanY/MMPlayerView#23]
hi thanks for this library.
My question is when i click the 2. row in collection view,  1. row is starting to play.
How can I solve this ?

**Comment by MillmanY** [comment]
can you give me your code segment let me know what happen

**Comment by ismailtosun** [comment]
I used example. I closed to auto play. and put a play button centre the image view. 
in my view there are a 2 video. when i click 2.video it play's 1.video 

```
extension JoinViewController : JoinCellButtonsDelegate {
    
    func playButtonDelegate(at index: IndexPath) {
        if let jlist = self.joinAllAllowedInnoList , !jlist.isEmpty{
            if let videoKey = jlist[index.row].teaserVideo , !videoKey.isEmpty{
                let cell = joinCollect.cellForItem(at: index) as! JoinCell
                self.startLoading()
                cell.playButton.isHidden = true
            }
        }
    }
}
```

**Comment by MillmanY** [comment]
Are you reset "playerLayer.playView" <----- to new indexPath view ??

**Comment by ismailtosun** [comment]
how can i do this ? I'm new at swift.

**Comment by ismailtosun** [comment]
@MillmanY I send my code as email ? please help me :)

**Comment by MillmanY** [comment]
Hi , are you want play video by select cell ? or you want to change contentoffset to play

**Comment by ismailtosun** [comment]
yes play video by select cell

1 Şub 2018 Per, saat 12:08 tarihinde Millman Yang <notifications@github.com>
şunu yazdı:

**Comment by ismailtosun** [comment]
@MillmanY  Yes play video by selected cell

**Comment by MillmanY** [comment]
func collectionView(_ collectionView: UICollectionView, didSelectItemAt indexPath: IndexPath) {
        //didSelect..
          if let cell =  collectionView.cellForItem(at: indexPath) as? YourCell {
              mmPlayerLayer.playView = cell.yourImageView
          

            mmPlayerLayer.set(url: cell.data?.play_Url, state: { (status) in
                switch status {
                    .......
            })

          }
        }
