### ISSUE TITLE
LandSpace button

### ISSUE THREAD

**Issue by ismailtosun** [MillmanY/MMPlayerView#27]
Hi, I put a button to covera cell. When I click button video will be play in fullscreen view 
How can I do this ? Any help ? 

what I did in CoverA cell 

```
@IBAction func btnFullAction(_ sender: Any) {
        
        let full = UIStoryboard.init(name: "Main", bundle: nil).instantiateViewController(withIdentifier: "FullScreenViewController") as! FullScreenViewController
        MMLandscapeWindow.shared.makeKey(root: full, playLayer: self.playLayer!, completed: {
            print("landscape completed")
            //self.playerCollect.isScrollEnabled = true
        })
    }
```

**Comment by ismailtosun** [comment]
@MillmanY  help please ?

**Comment by ismailtosun** [comment]
someone help me please ?

**Comment by MillmanY** [comment]
You also need implement function

    func application(_ application: UIApplication, supportedInterfaceOrientationsFor window: UIWindow?) -> UIInterfaceOrientationMask {
        
        if window == MMLandscapeWindow.shared {
            return .allButUpsideDown
        } else {
            return .portrait
        }
    }

in Appdelegate
