### ISSUE TITLE
Make video play from starting even if cached in collection view

### ISSUE THREAD

**Issue by devsujith** [MillmanY/MMPlayerView#31]
Hi,
I was wondering if there is a way to make video play from starting even if it is cached in memory, 
so that it will start playing faster since its cached.

**Comment by nvduc2910** [comment]
I hope that too. I want it play immediately when it already cached.

**Comment by Aragunz** [comment]
` if mainPlayerCoverView().playLayer?.player?.currentItem?.status == .readyToPlay {
                mainPlayerCoverView().playLayer?.player?.seek(to: kCMTimeZero, toleranceBefore: kCMTimeZero, toleranceAfter: kCMTimeZero)
            }`
Here it is the layer from Xib file containing player, just seek video from the begining.
