### ISSUE TITLE
How to  remove push transition 

### ISSUE THREAD

**Issue by nvduc2910** [MillmanY/MMPlayerView#32]
Hello, 

I want to remove custom transition to other viewcontroller that I don't want pass the video. 

Because now if I don't implement PassViewToProtocol in other viewcontroller I get frozen. how can I fix that issue.

Thank you so much.

**Comment by MillmanY** [comment]
3.1.0 
change 
        self.navigationController?.mmPlayerTransition.push.pass(setting: {_ in })
and
        self.navigationController?.mmPlayerTransition.push.enableCustomTransition = false

**Comment by nvduc2910** [comment]
Thank for reply me. 

but I have an issue . can you help me

I have three viewcontrollers  A B C

I pass videoPlayer from A -> B 
then in B I disable enableCustomTransition for pushing to C controller. 
then C pop back B ( C -> B) and in B I enable enableCustomTransition 

But I can not pass videoPlayer back to A 

Can you help me
