### ISSUE TITLE
MMPlayerFromProtocol Not work totally

### ISSUE THREAD

**Issue by nvduc2910** [MillmanY/MMPlayerView#33]
I have an issue with that. 

I have a tabbar with three tabbar items. just call it is A B C 

In A viewcontroller I extension MMPlayerFromProtocol
In B viewcontroller  I extension MMPlayerFromProtocol

then in viewcontroller B I try to pass Player to another viewController but  MMPlayerFromProtocol raised in A 

Can you explain why? 

Thank you so much.

**Comment by MillmanY** [comment]
push or present view controller ?

**Comment by MillmanY** [comment]
when you go to B try to change value MMplayerFromProtocol willPassView return false in A

**Comment by nvduc2910** [comment]
It not work because MMplayerFromProtocol just raised on vc A . not happening in vc B .

Please check.

**Comment by MillmanY** [comment]
Hi, can you try 3.1.4 again
I think this issue its fixed

when you push try this in your tab
A willPassView return false
B willPassView return true
C willPassView return false
