### ISSUE TITLE
How define when video has been loaded?

### ISSUE THREAD

**Issue by NikKovIos** [MillmanY/MMPlayerView#34]
Is there a completion or something like this for `startLoading()`?

I have a collectionView. In cell there is a video. When cell is dequeuing the video starts loading. autoPlay is false. I want to manually start the video after it get loaded. How can i achieve that?

**Comment by MandeepSingh1** [comment]
With the help of MMPlayer instance you can manually start the video. Try this line

Your MMPlayerInstance.player?.play() like below I have call it using my player instance

self.mmPlayerLayer.player?.play()
