### ISSUE TITLE
Navigation issue

### ISSUE THREAD

**Issue by Rogho** [MillmanY/MMPlayerView#38]
After navigating back from detail view controller, main collection view doesn't show the video view.

**Comment by Rogho** [comment]
For detail, while navigating back the method "backReplaceSuperView" from "MMPlayerFromProtocol" is not being called.

**Comment by MillmanY** [comment]
Hi, can you try 3.1.4 again
I think this issue its fixed

**Comment by Rogho** [comment]
I solved it by making some changes in code. 
Thanks for help though.
 Awesome library. **Best wishes**.
