### ISSUE TITLE
How to add custom button on seek bar?

### ISSUE THREAD

**Issue by Kristaps89** [MillmanY/MMPlayerView#4]
This is very useful project.
I want to add "Full screen" button on seek bar.
![fullscreen button](https://user-images.githubusercontent.com/26663174/30142986-24653374-93b6-11e7-8385-21b48840cd20.png)
Please let me know how can I do.
regard

**Comment by MillmanY** [comment]
You need custom your CoverView and use "replace(cover: ##Your View##)",Find Example/CoverView path and design your custom UI like that

**Comment by ismailtosun** [comment]
@Kristaps89  Can u share your fullscreen button action code with me ?
