### ISSUE TITLE
play video for in collection view inside tableview

### ISSUE THREAD

**Issue by praveen4D2** [MillmanY/MMPlayerView#40]
How to play video for uitableview inside collection view like instagram ?

**Comment by praveen4D2** [comment]
How to play video for uitableview inside collection view like instagram ?

**Comment by praveen4D2** [comment]
How to play video in collection view inside the tableview ?

**Comment by MillmanY** [comment]
How about like this ?
vc.mmplayer.playView = vc.tableView.cellForRow(at: XXX).collectView.cellForRow(at: XXX).yourVIew
