### ISSUE TITLE
Background Sound Play

### ISSUE THREAD

**Issue by isilsucitim** [MillmanY/MMPlayerView#44]
hi, 

How do I get my MMPlayerView to play while app is in background?

**Comment by MillmanY** [comment]
You mean play the audio when press Home key ?

**Comment by nikhil191090** [comment]
@MillmanY @byrem6 I am also facing this issue. video still in the background playing so the sound is coming. mmplayer.player.pause() did not work.

**Comment by MillmanY** [comment]
when you dismiss viewcotroller check your deinit() function have called , if not the viewcontroller  is memory leak

**Comment by nikhil191090** [comment]
@MillmanY Can u please elaborate what actually I have to do.
 func back() 
{
    self.mmPlayerLayer.player?.rate = 0
        self.mmPlayerLayer.player?.pause()
        self.dismiss(animated: true, completion: nil)
}
This is my code but sometimes it work sometimes video played in background volume

**Comment by MillmanY** [comment]
add deinit() in your class help you check when you dismiss viewcontroller this class was dealloc
If you use closure or delegate in this class, check you have add [weak XXX] [unowned XXX] in your closure and define delegate variable for weak prevent cycle reference
