### ISSUE TITLE
Sound not working 

### ISSUE THREAD

**Issue by raza08** [MillmanY/MMPlayerView#49]
Hello,
I'm using MMPlayerView to play video url , video is playing fine but sound not working ,not able to hear sounds so what should I do to get sound in device.

**Comment by MandeepSingh1** [comment]
Check Whether your phone is in silent mode, may be thats why you are not being able to hear the voice of your video probably.

**Comment by raza08** [comment]
@MandeepSingh1 I've already checked to my phone is not in silent mode. After that I've used 
`        try! AVAudioSession.sharedInstance().setCategory(AVAudioSessionCategoryPlayback, with: [])
`
that code in `viewDidLoad()` and then it's working fine.

**Comment by MandeepSingh1** [comment]
Just put in Appdelegate that would be better.

**Comment by MandeepSingh1** [comment]
If your issue has been resolved then closed this thread also.

**Comment by raza08** [comment]
Okay Thank you.

**Comment by olivinesguerra** [comment]
still not playing :D any work around
