### ISSUE TITLE
Thumb Issues

### ISSUE THREAD

**Issue by ravigangwar1991** [MillmanY/MMPlayerView#5]
I am Using Player in tableViewCell when next video is playing then previous Video thumb is shown in Player. can you suggest any solution or improve in library.

**Comment by MillmanY** [comment]
player.playView  = newCellImage <- when set this it will clear your player, or you can set playView = nil when you are scrolling 
player.thumbImageView.image <- If you play on cell you don't need to set this, because of your image is on your cell

**Comment by ravigangwar1991** [comment]
i have Already tried these thing but can't got any solution.
