### ISSUE TITLE
Memory leak when select full screen

### ISSUE THREAD

**Issue by nvduc2910** [MillmanY/MMPlayerView#50]
ViewController 
    CollectionView
        CollectionViewCell

Play full screen video mode from collectionViewCell then pop this viewcontroller, I noted this viewcontroller doesn't deinit called. 

But if I don't select full screen from collectionview then pop this viewcontroller will raise the deinit function.

Can you check.

![screen shot 2018-08-14 at 4 02 34 pm](https://user-images.githubusercontent.com/12984583/44082632-fd33e722-9fdb-11e8-9df4-b6363ebfb8b3.png)

**Comment by lassekallesoe** [comment]
the same issue. please check.

**Comment by ducnv2910** [comment]
I got this issue too . please check . thank you.

**Comment by MillmanY** [comment]
I check in Swift5, when you back protrait, LandscapeWindow was dismiss
