### ISSUE TITLE
Getting Previous video Screen shot while playing next Video

### ISSUE THREAD

**Issue by Rajat2595** [MillmanY/MMPlayerView#52]
Hello, There I am getting one serious issue I am getting the previous video end part screenshot while playing the next video in the table view do you have any idea whats going on here?

**Comment by Gopal06bca** [comment]
We are also facing the same issue. Kindly assist us as soon as possible.

**Comment by TysonVignesh** [comment]
@MillmanY @Rajat2595 @Gopal06bca is this issue resolved?
