### ISSUE TITLE
How to pass video with Present transition

### ISSUE THREAD

**Issue by Cez95** [MillmanY/MMPlayerView#55]
I am trying to pass the layer in a present transition (modal) and I don't want to re-download the video after I segue. This is my current implementation but it doesn't work properly

First VC:
    // Used as the layer to play video for cells that display video
    public let mmPlayerLayer: MMPlayerLayer = {
        let view = MMPlayerLayer()
        view.cacheType = .memory(count: 5)
        view.coverFitType = .fitToPlayerView
        view.videoGravity = AVLayerVideoGravity.resizeAspectFill
//        view.autoPlay = true
        view.player?.isMuted = true
        return view
    }()
            let vc = VideoVC(nibName: nil, bundle: nil)
            self.prepare(for: UIStoryboardSegue(identifier: SEGUE_TO_VIDEO, source: self, destination: vc), sender: post)
            self.mmPlayerTransition.present.pass { (_) in}
            self.present(vc, animated: true, completion: {})

extension FirstVC: MMPlayerFromProtocol {
    var passPlayer: MMPlayerLayer {
        get {
            return self.mmPlayerLayer
        }
        
    }
    func transitionWillStart() {
        
    }
    
    func transitionCompleted() {
    }
    
}

Second VC:

    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)

        // Start Video
        self.mmPlayerTransition.present.pass { (config) in
            config.duration = 0.3
        }

    }

    private lazy var mmPlayerLayer: MMPlayerLayer = {
        let view = MMPlayerLayer()
        view.cacheType = .memory(count: 5)
        view.coverFitType = .fitToPlayerView
        view.videoGravity = AVLayerVideoGravity.resizeAspectFill
        view.autoPlay = true
        view.player?.isMuted = true
        return view
    }()

extension VideoVC: MMPlayerToProtocol {
    var containerView: UIView {
        get {
            return self.videoViewThumbnail
        }
    }
    
    func transitionCompleted(player: MMPlayerLayer) {
       self.mmPlayerLayer = player
    }
}

**Comment by MillmanY** [comment]
It seen okay, second VC mmpalyer dont init again

    fileprivate var playerLayer: MMPlayerLayer?

In your consle are print "Need Called setView" this line ??

**Comment by Cez95** [comment]
That didnt do it.

With that implementation a clear screen appears with no video

**Comment by Cez95** [comment]
Where am I suppose to print out "Need Called setView"?

**Comment by Cez95** [comment]
Is it possible to pass the downloaded video and just pass that data. It seems like passing the layer is a force and makes code non-reusable

**Comment by MillmanY** [comment]
if you play on first , it can play well on second like sample, i just want know when you push second view, in your consle see about string "Need Called setView"

**Comment by MillmanY** [comment]
What is your mmpalyer version ??

**Comment by Cez95** [comment]
Im using 3.1.4

**Comment by MillmanY** [comment]
My sample work fine, just check this image in your project

**Comment by MillmanY** [comment]
My sample work fine, so when you error are you see the string in console ?

**Comment by MillmanY** [comment]
Can i ask why you ("let vc = VideoVC(nibName: nil, bundle: nil)") nibName is nil , you create subview in code ? if you are you need create your "videoViewThumbnail" before present

**Comment by Cez95** [comment]
Yea i do all it through code. Let me try one sec
