### ISSUE TITLE
Video is playing without Cover View

### ISSUE THREAD

**Issue by amitsingh103** [MillmanY/MMPlayerView#57]
Hello Team,
   
   I am using MMPlayerView with collectionview with pagination. But when I call webservice to get more data with pagination then Video plays without coverview, i.e only sound is playing , no video preview avaialable for that video. When I scroll my collection view cell then go back to that cell then it plays correctly.Please help me regarding this issue.

Thanks

**Comment by MillmanY** [comment]
paste your issue code here let me check :)
