### ISSUE TITLE
App Getting crash in iOS 10.3.1

### ISSUE THREAD

**Issue by HemenduK** [MillmanY/MMPlayerView#58]
even in demo also getting crashed after end of the video play.
Steps:
1. run App in iOS 10.3.1
2. Autoplay video 1 from the list
3. dont scroll until video end.
4. video end.
5. scroll tableview
6. App get crashed.

MMPlayerView_Example[44893:468476] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'An instance 0x600000860c40 of class MMPlayerView.MMPlayerItem was deallocated while key value observers were still registered with it. Current observation info: <NSKeyValueObservationInfo 0x600000421a00> (
<NSKeyValueObservance 0x600000253aa0: Observer: 0x600000254040, Key path: status, Options: <New: NO, Old: NO, Prior: NO> Context: 0x0, Property: 0x608000245340>
<NSKeyValueObservance 0x600000253e30: Observer: 0x60000024d110, Key path: playbackLikelyToKeepUp, Options: <New: NO, Old: NO, Prior: NO> Context: 0x0, Property: 0x600000058ba0>
<NSKeyValueObservance 0x600000254df0: Observer: 0x6000002551b0, Key path: playbackBufferEmpty, Options: <New: NO, Old: NO, Prior: NO> Context: 0x0, Property: 0x600000248370>

*** First throw call stack:
(
	0   CoreFoundation                      0x0000000102e4eb0b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x0000000102543141 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000102eb7625 +[NSException raise:format:] + 197
	3   Foundation                          0x000000010207eb53 NSKVODeallocate + 294
	4   libobjc.A.dylib                     0x0000000102557b8e _ZN11objc_object17sidetable_releaseEb + 202
	5   AVFoundation                        0x0000000102b3426b -[AVClientBlockKVONotifier dealloc] + 186
	6   libobjc.A.dylib                     0x0000000102557b8e _ZN11objc_object17sidetable_releaseEb + 202
	7   AVFoundation                        0x0000000102b354a5 -[AVKeyPathDependency dealloc] + 136
	8   libobjc.A.dylib                     0x0000000102557b8e _ZN11objc_object17sidetable_releaseEb + 202
	9   CoreFoundation                      0x0000000102dcfb86 -[__NSSetM dealloc] + 86
	10  libobjc.A.dylib                     0x0000000102557b8e _ZN11objc_object17sidetable_releaseEb + 202
	11  AVFoundation                        0x0000000102b34fc7 -[AVKeyPathDependencyManager dealloc] + 81
	12  libobjc.A.dylib                     0x0000000102557b8e _ZN11objc_object17sidetable_releaseEb + 202
	13  AVFoundation                        0x0000000102b35e97 -[AVKeyPathFlattener dealloc] + 61
	14  Foundation                          0x000000010207ea8d NSKVODeallocate + 96
	15  libobjc.A.dylib                     0x0000000102557b8e _ZN11objc_object17sidetable_releaseEb + 202
	16  AVFoundation                        0x0000000102a34e73 -[AVPlayerLayer _stopObservingPlayer:] + 258
	17  libdispatch.dylib                   0x00000001072474a6 _dispatch_call_block_and_release + 12
	18  libdispatch.dylib                   0x000000010727005c _dispatch_client_callout + 8
	19  libdispatch.dylib                   0x000000010724e94f _dispatch_queue_serial_drain + 221
	20  libdispatch.dylib                   0x000000010724f669 _dispatch_queue_invoke + 1084
	21  libdispatch.dylib                   0x000000010724fb32 _dispatch_queue_override_invoke + 654
	22  libdispatch.dylib                   0x0000000107251ec4 _dispatch_root_queue_drain + 634
	23  libdispatch.dylib                   0x0000000107251bef _dispatch_worker_thread3 + 123
	24  libsystem_pthread.dylib             0x000000010760b169 _pthread_wqthread + 1387
	25  libsystem_pthread.dylib             0x000000010760abe9 start_wqthread + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by MillmanY** [comment]
Fix on 4.1.7
