### ISSUE TITLE
Command failed due to signal: Abort trap: 6. Using Xcode 9 with swift 3.2

### ISSUE THREAD

**Issue by ghost** [MillmanY/MMPlayerView#6]
Stored value type does not match pointer operand type!
  store i64 %1, i32* %14, align 4, !dbg !3254
 i32Stored value type does not match pointer operand type!
  store i64 %2, i32* %17, align 4, !dbg !3254
 i32Stored value type does not match pointer operand type!
  store %swift.refcounted* %3, i64* %19, align 4, !dbg !3254
 i64<unknown>:0: error: fatal error encountered during compilation; please file a bug report with your project and the crash log
<unknown>:0: note: Broken function found, compilation aborted!
0  swift                    0x000000010e0badba PrintStackTraceSignalHandler(void*) + 42
1  swift                    0x000000010e0ba1f6 SignalHandler(int) + 662
2  libsystem_platform.dylib 0x00007fffd6aabb3a _sigtramp + 26
3  libsystem_platform.dylib 0x000000010f865551 _sigtramp + 953915953
4  libsystem_c.dylib        0x00007fffd6930420 abort + 129
5  swift                    0x000000010aa29fe7 swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*)::$_0::__invoke(void*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool) + 551
6  swift                    0x000000010e0783fb llvm::report_fatal_error(llvm::Twine const&, bool) + 571
7  swift                    0x000000010e0781ba llvm::report_fatal_error(char const*, bool) + 42
8  swift                    0x000000010e04e6b6 (anonymous namespace)::VerifierLegacyPass::runOnFunction(llvm::Function&) + 54
9  swift                    0x000000010dffbaaa llvm::FPPassManager::runOnFunction(llvm::Function&) + 506
10 swift                    0x000000010e003609 llvm::legacy::FunctionPassManagerImpl::run(llvm::Function&) + 377
11 swift                    0x000000010e0033fa llvm::legacy::FunctionPassManager::run(llvm::Function&) + 410
12 swift                    0x000000010aba3778 swift::performLLVM(swift::IRGenOptions&, swift::DiagnosticEngine*, llvm::sys::SmartMutex<false>*, llvm::GlobalVariable*, llvm::Module*, llvm::TargetMachine*, swift::version::Version const&, llvm::StringRef, swift::UnifiedStatsReporter*) + 5016
13 swift                    0x000000010aa2ec18 performCompile(swift::CompilerInstance&, swift::CompilerInvocation&, llvm::ArrayRef<char const*>, int&, swift::FrontendObserver*, swift::UnifiedStatsReporter*) + 19496
14 swift                    0x000000010aa28784 swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*) + 7716
15 swift                    0x000000010a9dd6a8 main + 12248
16 libdyld.dylib            0x00007fffd689c235 start + 1
Stack dump:

**Comment by ghost** [comment]
MMPlayerView version = 2.1.0
tried 2.1.7(still this error)

**Comment by MillmanY** [comment]
2.1.8 Fix this issue
