### ISSUE TITLE
Stop showing the loader and play next video smoothly

### ISSUE THREAD

**Issue by khush004** [MillmanY/MMPlayerView#60]
Hello, Thank you for this awesome library. I am facing some issues while loading a video it shows Activity loader and black screen for a moment I don't want that loader and black screen I just want it to play smoothly without any loader and my server is fast and I don't have any internet issue.

How do I achieve this? Please help!

**Comment by MillmanY** [comment]
mmPlayerLayer.progressType = .none
mmPlayerLayer.backgroundColor = UIColor.white.cgColor
??
