### ISSUE TITLE
Swift 5 support?

### ISSUE THREAD

**Issue by ghost** [MillmanY/MMPlayerView#61]
I tried to add Swift 5 integration, and I got this error:
Fatal error: could not demangle keypath type from '����XD': file /BuildRoot/Library/Caches/com.apple.xbs/Sources/swiftlang/swiftlang-1001.2.63.12/swift/stdlib/public/core/KeyPath.swift, line 2611

Could @MillmanY please help with this bug?

Many thanks

**Comment by MillmanY** [comment]
I update my pod support on swift5 version 5.0.0
