### ISSUE TITLE
POD install

### ISSUE THREAD

**Issue by JesseRubio** [MillmanY/MMPlayerView#7]
I've tried several ways of installing the pod file but keeps giving me the following errors:

[!] Unable to find a specification for `MMPlayerView (~> 3.0.2)`
[!] Unable to find a specification for `MMPlayerView (= 3.0.2)`
[!] Unable to find a specification for `MMPlayerView`

note: I was trying to install them individually, not all together as it shows above.

**Comment by MillmanY** [comment]
try  "pod repo update" than "pod install" again

**Comment by JesseRubio** [comment]
YES! It worked, thanks!!

**Comment by MillmanY** [comment]
👍
