### ISSUE TITLE
How can i stop the video from playing when the cell is not in view

### ISSUE THREAD

**Issue by GurdevSingh94** [MillmanY/MMPlayerView#70]
How can i stop the video from playing when the cell is not in view, it continues on playing

**Comment by MillmanY** [comment]
When you contentoffset change , check your cell whether is visiable on window

**Comment by GurdevSingh94** [comment]
could you please provide a example

**Comment by MandeepSingh1** [comment]
Hey GurdevSingh94 use this below code to stop the video when cell is not in view hierarchy.

     //MARK:- Add Observer For fetch Current Scroll IndexPAth
     override func observeValue(forKeyPath keyPath: String?, of object: Any?, change: [NSKeyValueChangeKey : Any]?, context: UnsafeMutableRawPointer?) {
        //This logic means that user is staying on the timeline screen only.
        if keyPath == "contentOffset"  {
            self.startVideoForCell()
        } else {
            super.observeValue(forKeyPath: keyPath, of: object, change: change, context: context)
        }
    }
    
    func startVideoForCell() {
        self.updateByContentOffset()
        NSObject.cancelPreviousPerformRequests(withTarget: self)
        self.perform(#selector(startLoading), with: nil, afterDelay: 0.3)
    }
    
    func updateByContentOffset() {
        
        let p = CGPoint(x: self.tableView!.frame.width/2, y: self.tableView!.contentOffset.y + self.tableView!.frame.width/2)
        
        if let path = self.tableView!.indexPathForRow(at: p),
            self.presentedViewController == nil {
            self.updateCell(at: path)
        }
    }
   
    func updateCell(at indexPath: IndexPath) {
        
        if let cell = self.tableView.cellForRow(at: indexPath) as? TimelineFeedCellXP, self.arrayPostData.count > 0 {
            // this thumb use when transition start and your video dosent start
            let postModel = self.arrayPostData[indexPath.row]
            
            //This means it contains video and text is not compulsory.
            if postModel.video_flag == 1 {
                
                if let videoURL = URL(string: postModel.image_url ?? "") {
                    // set url prepare to load
                    self.videoPlayer?.set(url: videoURL, state: { (status) in
                        switch status {
                            
                        case .playing:
                            if let postModel = cell.postModelInfo {
                                self.viewVideoByCurrentUser(postModel: postModel)
                            }
                        case .failed(err: _):
                            if Reachability.isConnectedToNetwork() == false {
                                self.addRefreshView()
                            } else {
                                self.refreshModelViews?.removeFromSuperview()
                            }
                        default: break
                        }
                    })
                }
            } else {
                self.destroyMMPlayerInstance()
            }
        }
    }

       func destroyMMPlayerInstance() {
        
        if let xpPlayer = self.videoPlayer, xpPlayer.playView != nil {
            xpPlayer.player?.pause()
            xpPlayer.playView = nil
        }
    }

**Comment by fukemy** [comment]
hi @MillmanY , can u share full code to handle it? i found some property not found, such as "startLoading"....
