### ISSUE TITLE
Play video while still downloading

### ISSUE THREAD

**Issue by xvicient21** [MillmanY/MMPlayerView#72]
Hi,

I'm using MMPlayerDownloader to download a list of m3u8 files. I'm trying to reproduce while downloader it's still downloading the video but MMPlayerDownloader.shared.localFileFrom return nil for not completely download videos. ¿Is there any option to start playing a video while it's downloading? Like https://github.com/neekeetab/CachingPlayerItem

Thx!

**Comment by MillmanY** [comment]
1. MMPlayerDownloader.shared.download(url: downloadURL)
2. Just call
            mmPlayerLayer.set(url: playURL)
            mmPlayerLayer.resume()
3. When download finished, reload url from player, it will check cache first, then check disk whether exist
