### ISSUE TITLE
Cannot invoke initializer for type 'MMLandscapeWindow' with no arguments

### ISSUE THREAD

**Issue by venki464** [MillmanY/MMPlayerView#78]
<img width="495" alt="Screenshot 2019-08-07 at 1 43 22 PM" src="https://user-images.githubusercontent.com/4987283/62606201-51d8e280-b919-11e9-8b4f-9a420a3310f2.png">

This is happening only in iOS 13 beta 5

**Comment by MillmanY** [comment]
I think you need pod update, use "playerLayer.fullScreenWhenLandscape" control rotate action

**Comment by HuseyinVural** [comment]
unfortunately, the problem persists in the main version
