### ISSUE TITLE
How to stop play video, if there is not only video types? For example in collectionView list there are image types also? 

### ISSUE THREAD

**Issue by KanybekMomukeyev** [MillmanY/MMPlayerView#8]
How to stop play video?
For example, in collectionView list there are also image types?
Like this:
[ Video type ]
[ Image type ]
[ Video type ]
[ Video type ]
[ Video type ]
[ Image type ]
[ Image type ]

**Comment by MillmanY** [comment]
1. set player.playView = nil when type equal Image to clear current video
2. mmPlayerLayer.player?.pause()

**Comment by MandeepSingh1** [comment]
Hi am also using the same way to Play Video in Collection View. There is a list of images and videos showing in collection view.

[ Video type ]
[ Image type ]
[ Video type ]
[ Video type ]
[ Video type ]
[ Image type ]
[ Image type ]

fileprivate func updateCell(at indexPath: IndexPath) {
        
        if let cell = self.collectionView!.cellForItem(at: indexPath) as? TimelineFeedCell {
            // this thumb use when transition start and your video dosent start
            
           let postDict = self.arrayPostData[indexPath.item]
            
            print(indexPath.item)
            
            if postDict.video_flag == 0 {
                
                mmPlayerLayer.playView = nil
                mmPlayerLayer.player?.pause()
                mmPlayerLayer.playUrl = nil
                
            } else {
                
                mmPlayerLayer.thumbImageView.image = cell.postImageView.image
                // set video where to play
                if !MMLandscapeWindow.shared.isKeyWindow {
                    mmPlayerLayer.playView = cell.postImageView
                }
                
                // set url prepare to load
                mmPlayerLayer.set(url: URL(string: cell.postModelInfo?.image_url ?? ""), state: { (status) in
                    switch status {
                    case .failed(let err):
                        print("err", err)
                    case .ready:
                        print("Ready to Play")
                    case .playing:
                        print("Playing")
                    case .pause:
                        print("Pause")
                    case .end:
                        print("End")
                    default: break
                    }
                })
            }
        }
    }

Am using your function but Still am not able to stop the previous cell of video. Video is still playing but my current cell is of image. How can I resolve this issue. Please Help me

**Comment by fukemy** [comment]
i think the mmPlayerLayer will always point to newest cell, so the playerView is not correct cell
