### ISSUE TITLE
what about UITabbarController ?

### ISSUE THREAD

**Issue by ghimireprashant** [MillmanY/MMPlayerView#85]
does mmplayerview work on tabbar?

thanks

**Comment by MillmanY** [comment]
yes its work

**Comment by ghimireprashant** [comment]
please provide me the instruction. 
i have tried 
```
     if let vc = UIStoryboard.init(name: "Main", bundle: nil).instantiateViewController(withIdentifier: "DetailViewController") as? DetailViewController {
            vc.data = DemoSource.shared.demoData[indexPath.row]
        self.tabBarController?.present(vc, animated: true, completion: nil)
```
for presenting.
and sinking view
`     (self.presentationController as? MMPlayerPassViewPresentatinController)?.shrinkView()
`
i want to display floating player in top of tabbar like youtube.
but i am not able make it work.
thanks

**Comment by MillmanY** [comment]
[image: 截圖 2019-10-16 下午2.45.31.png]
I try to add tabViewController its work fine, can you print
(self.presentationController as? MMPlayerPassViewPresentatinController)  to
check nil or not ?

Prashant Ghimire <notifications@github.com> 於 2019年10月16日 週三 下午2:20寫道：

**Comment by MillmanY** [comment]
[image: 截圖 2019-10-16 下午2.45.19.png]

Millman Yang <millmanyang@gmail.com> 於 2019年10月16日 週三 下午2:48寫道：

**Comment by ghimireprashant** [comment]
hello @MillmanY  
(self.presentationController as? MMPlayerPassViewPresentatinController) is nil.
so i am not able to shrinkView 
thanks

**Comment by ghimireprashant** [comment]
Just added 
```
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        self.mmPlayerTransition.present.pass { (config) in
            config.duration = 0.3
        }
    }
```
and not nil anymore.
but still not able to shrinkView
:(

**Comment by ghimireprashant** [comment]
previously issued are fixed
hello @MillmanY 
my recent issue is when i try to dismiss shrinkView by swipe i am not able to present again the detailviewcontroller. and when i dismiss shrinkView from other viewController shrinkView goes on top 
```
    self.dismiss(animated: true, completion: {
      self.presentingViewController?.dismiss(animated: true, completion: nil)
    })
```
check the first image shrinkview is overlapping tabbar how to pass origin for that shrinkview.
thanks
![Simulator Screen Shot - iPhone Xʀ - 2019-10-18 at 22 43 52](https://user-images.githubusercontent.com/16249616/67113281-ce7d1c80-f1f8-11e9-8c41-4f41785ac645.png)
![Simulator Screen Shot - iPhone Xʀ - 2019-10-18 at 19 56 30](https://user-images.githubusercontent.com/16249616/67101696-d4b3ce80-f1e1-11e9-89b3-4c5d85ac9c5a.png)
