### ISSUE TITLE
code issue

### ISSUE THREAD

**Issue by rossman22590** [MillmanY/MMPlayerView#86]
error : Type 'MMLandscapeWindow' has no member 'shared' please help

-------------------
my code:

 fileprivate func landscapeAction() {

    if UIDevice.current.orientation.isLandscape {
         let full = UIStoryboard.init(name: "LoggedInTabbar", bundle: nil).instantiateViewController(withIdentifier: "FullScreenVC") as! FullScreenVC
        MMLandscapeWindow.shared.makeKey(root: full, playLayer: self.mmPlayerLayer, completed: {
            print("landscape completed")
        })
    }
}

**Comment by MillmanY** [comment]
New version is duplicated this function, I change it in my example

**Comment by rossman22590** [comment]
is pod update?

**Comment by MillmanY** [comment]
5.1.3 try again
