### ISSUE TITLE
Crashing application when build on iOS 13

### ISSUE THREAD

**Issue by fuadwaheed** [MillmanY/MMPlayerView#87]
Terminating app due to uncaught exception 'NSRangeException', reason: 'Cannot remove an observer <_NSKeyValueObservation 0x600001555230> for the key path "videoRect" from <MMPlayerView.MMPlayerLayer 0x7fc0d3eabe30> because it is not registered as an observer.'

I am facing this issue after i build the application on iOS 13. i tried on iOS 12 and it works fine, what i can do to remove this error. This error occurs when i pop the view in which mmplayer has been implemented.

**Comment by MillmanY** [comment]
Which lib version are you use?

**Comment by fuadwaheed** [comment]
I am using 5.0.8

**Comment by MillmanY** [comment]
Try to update to 5.1.3
