### ISSUE TITLE
crashing when go to back screen and also crashed when scroll the tableview

### ISSUE THREAD

**Issue by Mohsinraza880** [MillmanY/MMPlayerView#88]
Terminating app due to uncaught exception 'NSRangeException', reason: 'Cannot remove an observer <_NSKeyValueObservation 0x6000035b5920> for the key path "videoRect" from <MMPlayerView.MMPlayerLayer 0x7fb357c0ba60> because it is not registered as an observer.'

**Comment by MillmanY** [comment]
Which version are you use ??

**Comment by MillmanY** [comment]
Try to update 5.1.3
