### ISSUE TITLE
Any way to add subtitles or languages selector?

### ISSUE THREAD

**Issue by deibytb** [MillmanY/MMPlayerView#89]

**Comment by MillmanY** [comment]
ASAP :)

**Comment by MillmanY** [comment]
Try 5.1.4 I add first subTitle type .srt in code.

       public var subTitleFont: UIFont = UIFont.systemFont(ofSize: 17)
       public var subTitleDefaultTextColor: UIColor = UIColor.white
       public var subTitleLabelEdge: (bottom: CGFloat, left: CGFloat, right: CGFloat) = (20,10,10)
       enum SubTitleType {
          case srt(info: String)
       }
       let subTitleStr = Bundle.main.path(forResource: "test", ofType: "srt")!
            if let str = try? String.init(contentsOfFile: subTitleStr) {
                self.mmPlayerLayer.subTitleType = .srt(info: str)
            }
        }
