### ISSUE TITLE
Audio not playing when the device is in silent Mode

### ISSUE THREAD

**Issue by ArunDevOpsiOS** [MillmanY/MMPlayerView#9]
The Video is playing as it needs to but the issue is that when the device is in silent mode then the audio is not playing at all. I think that this issue is pointed here [URL](https://stackoverflow.com/questions/35289918/play-audio-when-device-in-silent-mode-ios-swift)  or maybe not.

**Comment by MillmanY** [comment]
do {
            try AVAudioSession.sharedInstance().setCategory(AVAudioSessionCategoryPlayback, with: [.mixWithOthers])
            try AVAudioSession.sharedInstance().setActive(true)
        } catch {}


I think this is not a part of lib, so you need setup by yourself when appdelegate launching

**Comment by MandeepSingh1** [comment]
Thanks MillmanY For your answer

**Comment by olivinesguerra** [comment]
still not playing even I set this code on AppDelegate

    do {
        try AVAudioSession.sharedInstance().setCategory(AVAudioSessionCategoryPlayback, with: [.mixWithOthers])
        try AVAudioSession.sharedInstance().setActive(true)
    } catch {}
