### ISSUE TITLE
Hello i am facing the same issue 

### ISSUE THREAD

**Issue by ioseagleteam** [MillmanY/MMPlayerView#90]
Terminating app due to uncaught exception 'NSRangeException', reason: 'Cannot remove an observer <_NSKeyValueObservation 0x600001487630> for the key path "videoRect" from <MMPlayerView.MMPlayerLayer 0x7f888ad806c0> because it is not registered as an observer.

**Comment by MillmanY** [comment]
pod repo update
pod update
The new version is "5.5.0"
