### ISSUE TITLE
crash: demo example will crash on iOS 12 

### ISSUE THREAD

**Issue by engsulta** [MillmanY/MMPlayerView#93]
you should weak import AVFoundation Manually in the MMPlayerView module build phases 
to prevent the crash

**Comment by engsulta** [comment]
<img width="878" alt="image" src="https://user-images.githubusercontent.com/34632263/71897000-f166ff00-315d-11ea-9cb1-746ad5a00a19.png">

**Comment by engsulta** [comment]
for more details 
https://stackoverflow.com/questions/43009124/dyld-not-found-avassetdownladtask

**Comment by MillmanY** [comment]
Fix this issue on 6.0.1
I found if you use "onTapGesture" in code, it will be crash when build.

Its a bug for apple
